Class = {}
Number = 1

Class[Number] = {}
Class[Number]["name"] = "Default"
Class[Number]["description"] = "This is the default class. No changes are made."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 20
Class[Number]["walkspeedmul"] = 1
Class[Number]["runspeedmul"] = 1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"none"}
Class[Number]["color"] = Color(255,255,255,255)
Class[Number]["icon"] = "models/Kleiner.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Juggernaut"
Class[Number]["description"] = "The ultimate tank. Juggernauts are equipped with heavily plated armor that has a 60% chance to absorb 10-20 damage. Juggernauts gain a 25% resistance to bullets. Juggernauts also gain a 10% resistance to explosives. Juggernauts cannot be healed."
Class[Number]["health"] = 100
Class[Number]["armor"] = 100
Class[Number]["stamina"] = 7
Class[Number]["walkspeedmul"] = 0.50
Class[Number]["runspeedmul"] = 0.50
Class[Number]["jumpmul"] = 0.75
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 4
Class[Number]["perks"] = {"Necro","FlakJacketMinor","Shield","Kevlar"}
Class[Number]["color"] = Color(200,200,0,255)
Class[Number]["icon"] = "models/Combine_Super_Soldier.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Assassin"
Class[Number]["description"] = "Assassins use special ammunition that is 300% more lethal when used on areas such as the skull, but it's 50% weaker on all other areas. Assassins absorb 10-30 damage from behind."
Class[Number]["health"] = 90
Class[Number]["armor"] = 10
Class[Number]["stamina"] = 25
Class[Number]["walkspeedmul"] = 0.75
Class[Number]["runspeedmul"] = 1.1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1.35
Class[Number]["fallmul"] = 0.75
Class[Number]["perks"] = {"HeadshotHunter","BackDoor"}
Class[Number]["color"] = Color(50,200,50,255)
Class[Number]["icon"] = "models/player/t_leet.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Zombie"
Class[Number]["description"] = "Zombies gain +1 health and armor every 3 seconds up to 75 and damage enemies based on distance in a 300 unit radius due to their toxic flesh. Zombies are also 100% weaker to headshots but 10% resistant to everywhere else. Zombies cannot heal."
Class[Number]["health"] = 50
Class[Number]["armor"] = 50
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.9
Class[Number]["runspeedmul"] = 0.75
Class[Number]["jumpmul"] = 0.80
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.25
Class[Number]["perks"] = {"DeadLife","BrainDamage","ArcLight","Necro"}
Class[Number]["color"] = Color(180,125,125,255)
Class[Number]["icon"] = "models/Zombie/Classic.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Demon Porn"
Class[Number]["description"] = "Flash gets off to massive demon cock. Demons trade life energy escaped from enemy wounds for bonus armor. For every 1 point of damage, 0.25 points of armor is added. Demons also have the lifesteal ability, which steals 20% of the damage done to another player up to 200 points of health. Demons cannot heal."
Class[Number]["health"] = 75
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 1
Class[Number]["runspeedmul"] = 1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0.9
Class[Number]["perks"] = {"SoulAbsorb","LifeSteal","Necro"}
Class[Number]["color"] = Color(150,0,150,255)
Class[Number]["icon"] = "models/player/skeleton.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Void"
Class[Number]["description"] = "Voids don't entirely exist in this plain of existence. Voids reflect 25% of damage done to them at the cost of 25% less base damage but cannot reflect damage done by other methods of damage reflection. Voids slowly take damage over time. Voids cannot be healed."
Class[Number]["health"] = 100
Class[Number]["armor"] = 10
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.9
Class[Number]["runspeedmul"] = 0.9
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0
Class[Number]["perks"] = {"ReflectDamage", "Annoying", "Necro"}
Class[Number]["color"] = Color(200,200,200,255)
Class[Number]["icon"] = "models/Zombie/Poison.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Phantom"
Class[Number]["description"] = "Phantoms have a 25% chance to completely dodge an attack, and have a strange aura around them that causes people's vision to shake. Phantoms cannot be healed."
Class[Number]["health"] = 75
Class[Number]["armor"] = 25
Class[Number]["stamina"] = 25
Class[Number]["walkspeedmul"] = 1
Class[Number]["runspeedmul"] = 1.2
Class[Number]["jumpmul"] = 1.1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0
Class[Number]["perks"] = {"Evasion","Mystical","Necro"}
Class[Number]["color"] = Color(200,200,225,255)
Class[Number]["icon"] = "models/player/corpse1.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Field Medic"
Class[Number]["description"] = "Field Medics slowly restore 1 health every second to nearby allies on his team. This bonus is tripled on the medic. Medics also leech 1 point of health per second off of enemies in a 500 unit radius."
Class[Number]["health"] = 60
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 20
Class[Number]["walkspeedmul"] = 0.90
Class[Number]["runspeedmul"] = 1.1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"Medic","AuraLeech"}
Class[Number]["color"] = Color(255,10,10,255)
Class[Number]["icon"] = "models/Characters/Hostage_01.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Shredder"
Class[Number]["description"] = "25% of damage dealt to an enemy transfers to other enemies in a 1000 radius area around said enemy. Shredders have a unique allow armor that removes the base damage dealt by 10, but multiplies any remaining damage by 2."
Class[Number]["health"] = 80
Class[Number]["armor"] = 10
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.9
Class[Number]["runspeedmul"] = 0.9
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.1
Class[Number]["perks"] = {"Splash","Barter"}
Class[Number]["color"] = Color(150,200,200,255)
Class[Number]["icon"] = "models/player/ct_sas.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Marksman"
Class[Number]["description"] = "Gains the ability to grant critical strikes. Critical strikes stun your opponent for 0.25 seconds and do double damage. Every 2 points of base damage adds 1% chance to crit. Snipers also have a special type of shield amplification technology that expands when shot, causing snipers to resist 1% of all damage per 1 point of lost health, up to 50%, but causes the sniper's base damage to decrease by 50 but multiply by 3. "
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 30
Class[Number]["walkspeedmul"] = 0.75
Class[Number]["runspeedmul"] = 0.75
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 0.7
Class[Number]["fallmul"] = 0.8
Class[Number]["perks"] = {"Stunner","Survivor","Forced"}
Class[Number]["color"] = Color(255,255,0,255)
Class[Number]["icon"] = "models/player/t_guerilla.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Voltage"
Class[Number]["description"] = "Volts use special shield piercing ammo that does 1% more damage per point of shield; although overall damage is reduced by 25%. Volts also have a strong shield regeneration core that restores shields up to 100, but is highly experimental and will explode violently if you take damage while your shields are depleted. Each attack also steals armor based on 15% of damage dealt, Stacks up to 200 points of armor."
Class[Number]["health"] = 100
Class[Number]["armor"] = 100
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.87
Class[Number]["runspeedmul"] = 0.87
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.5
Class[Number]["perks"] = {"AP","ArmorSteal","Snackbar","ArmorDependant","ArmorRegen"}
Class[Number]["color"] = Color(0,100,0,255)
Class[Number]["icon"] = "models/barney.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Predator"
Class[Number]["description"] = "Gains the cloak ability which drains 1 armor every 5 seconds. Cloak amount is based on movement speed. Each attack also steals armor based on 15% of damage dealt, Stacks up to 200 points of armor."
Class[Number]["health"] = 20
Class[Number]["armor"] = 50
Class[Number]["stamina"] = 30
Class[Number]["walkspeedmul"] = 0.65
Class[Number]["runspeedmul"] = 1.1
Class[Number]["jumpmul"] = 1.25
Class[Number]["crouchmul"] = 0.75
Class[Number]["fallmul"] = 0.75
Class[Number]["perks"] = {"Cloak","ArmorSteal"}
Class[Number]["color"] = Color(25,100,200,255)
Class[Number]["icon"] = "models/stalker.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Benevolent Demon"
Class[Number]["description"] = "Damage dealt to Benevolent Demons have a 10% chance to convert damage into health."
Class[Number]["health"] = 125
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 20
Class[Number]["walkspeedmul"] = 0.9
Class[Number]["runspeedmul"] = 0.9
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0
Class[Number]["perks"] = {"Reversal"}
Class[Number]["color"] = Color(150,100,100,255)
Class[Number]["icon"] = "models/player/zombie_fast.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Trickster"
Class[Number]["description"] = "Tricksters can swap with any random player on the map once every 30 seconds if the Trickster's health is below 50. Explosive damage dealt by Tricksters turn into stackable stuns, for every 20 points of explosive damage, 1 second of stun is added. Tricksters cannot be healed."
Class[Number]["health"] = 125
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.90
Class[Number]["runspeedmul"] = 0.90
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0
Class[Number]["perks"] = {"Swap","Trap","Necro"}
Class[Number]["color"] = Color(200,200,225,255)
Class[Number]["icon"] = "models/player/gman_high.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Demonigga"
Class[Number]["description"] = "Demoniggas are for the aspiring pyrotechnist. Demoniggas deal 10% bonus damage whilst using explosives, and have a 50% resistance to explosive damage. Demoniggas also reflect 10% of explosive damage back to the attacker. Demoniggas also do 25% of damage dealt to an enemy to other enemies in a 1000 unit radius."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 25
Class[Number]["walkspeedmul"] = 0.8
Class[Number]["runspeedmul"] = 0.8
Class[Number]["jumpmul"] = 0.9
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.1
Class[Number]["perks"] = {"Explosive","FlakJacketMajor","Splash"}
Class[Number]["color"] = Color(180,0,0,255)
Class[Number]["icon"] = "models/vortigaunt.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Spy"
Class[Number]["description"] = "Spies can fake their death by creating a holographic corpse while turning invisible. The invisibility lasts until you damage someone. Spies grant a 100% critical strike chance while invisible. Spies cannot heal."
Class[Number]["health"] = 25
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 20
Class[Number]["walkspeedmul"] = 1
Class[Number]["runspeedmul"] = 1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"FakeDeath","Necro"}
Class[Number]["color"] = Color(200,100,100,255)
Class[Number]["icon"] = "models/player/spy.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "NIGGER SLAYER"
Class[Number]["description"] = "I am justice incarnate, brought forth to end the lives of those that are wasting breathing air and purge them of their foul presence. I am the NIGGER SLAYER, and you're niggery ends here, now. Drop to your knees and surrender, or you will face a war machine unlike ANY this world has ever seen. Nigger slayers start off with high health but loose it over time. 20 health is regained every kill."
Class[Number]["health"] = 300
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 10
Class[Number]["walkspeedmul"] = 0.65
Class[Number]["runspeedmul"] = 0.65
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 3
Class[Number]["perks"] = {"Slayer","Necro"}
Class[Number]["color"] = Color(255,233,127,255)
Class[Number]["icon"] = "models/serioussam/sam_stone_bfe.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Scatman"
Class[Number]["description"] = "Flash's Class. Gain 10% bonus damage at the cost of 30% incoming damage amplification. Scatmen gain health or loose health every 3 seconds. "
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 1.1
Class[Number]["runspeedmul"] = 1.1
Class[Number]["jumpmul"] = 1.5
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"DamageTrade","Poop"}
Class[Number]["color"] = Color(127, 111, 63,255)
Class[Number]["icon"] = "models/jessev92/player/misc/creepr.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Supercharged"
Class[Number]["description"] = " Creed's Class. Gains the supercharged perk, gives insane amount of agility in sacrifice of damage over time. Health regenerates while standing still. Gains the double jump ability which allows the player to jump twice in the air. Cannot be healed by other means."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 1.6
Class[Number]["runspeedmul"] = 1.6
Class[Number]["jumpmul"] = 1.25
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"Bleedout","Necro","DoubleJump"}
Class[Number]["color"] = Color(255, 255, 0,255)
Class[Number]["icon"] = "models/magnusson.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Shatterling"
Class[Number]["description"] = "As long as you have armor, each hit against you grants an entire second of damage immunity. During this immunity you are stunned. Immune to headshots. Takes 50% extra damage. Shatterlings cannot heal."
Class[Number]["health"] = 100
Class[Number]["armor"] = 100
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.6
Class[Number]["runspeedmul"] = 0.6
Class[Number]["jumpmul"] = 0.75
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.2
Class[Number]["perks"] = {"Shatter","Necro"}
Class[Number]["color"] = Color(100, 50, 255,255)
Class[Number]["icon"] = "models/bots/heavy_boss/bot_heavy_boss.mdl"