Class = {}
Number = 1

Class[Number] = {}
Class[Number]["name"] = "Default"
Class[Number]["description"] = "This is the default class. No changes are made."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 20
Class[Number]["walkspeedmul"] = 1
Class[Number]["runspeedmul"] = 1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"None"}
Class[Number]["color"] = Color(255,255,255,255)
Class[Number]["icon"] = "models/Kleiner.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Juggernaut"
Class[Number]["description"] = "Counters small arm damage such as shotguns, great for people who like being a human tank. Juggernauts are equipped with heavily plated armor that has a 60% chance to absorb 10-20 damage. Juggernauts gain a 25% resistance to damage dealt to the torso. Juggernauts also gain a 10% resistance to explosives. Juggernauts cannot be healed."
Class[Number]["health"] = 100
Class[Number]["armor"] = 100
Class[Number]["stamina"] = 7
Class[Number]["walkspeedmul"] = 0.50
Class[Number]["runspeedmul"] = 0.50
Class[Number]["jumpmul"] = 0.75
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 4
Class[Number]["perks"] = {"Necro","FlakJacketMinor","Shield","Kevlar"}
Class[Number]["color"] = Color(200,200,0,255)
Class[Number]["icon"] = "models/player/lordvipes/haloce/spartan_classic.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Anti-Tank"
Class[Number]["description"] = "Counters anyone who is tanky. Anti-Tanks do damage based on the enemy's health or armor; for every point of health or armor, anti-tanks deal 1% damage. For example an enemy with combined 200 health and armor will take double damage, but an enemy with combined 50 health and armor will take half damage."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 25
Class[Number]["walkspeedmul"] = 1.1
Class[Number]["runspeedmul"] = 1.1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"BasedHealthDamage"}
Class[Number]["color"] = Color(255,200,50,255)
Class[Number]["icon"] = "models/player/haroldlott.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Assassin"
Class[Number]["description"] = "Counters people trying to buttfuck you, good for people who are accurate. Assassins use special ammunition that is 300% more lethal when used on areas such as the skull, but it's 50% weaker on all other areas. The ammunition is also poison tipped, it does a bonus 2 damager per second for 5 seconds; the damage cannot stack, but the duration is reset to 5. Assassins absorb 10-30 damage from behind."
Class[Number]["health"] = 90
Class[Number]["armor"] = 10
Class[Number]["stamina"] = 25
Class[Number]["walkspeedmul"] = 0.75
Class[Number]["runspeedmul"] = 1.1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1.35
Class[Number]["fallmul"] = 0.75
Class[Number]["perks"] = {"HeadshotHunter","BackDoor","Drain"}
Class[Number]["color"] = Color(50,200,50,255)
Class[Number]["icon"] = "models/player/lordvipes/metal_gear_rising/gray_fox_playermodel_cvp.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Zombie"
Class[Number]["description"] = "Balanced class for people who want to have longer lives. Zombies gain +1 health and armor every 3 seconds up to 75 and damage enemies based on distance in a 300 unit radius due to their toxic flesh. Zombies are also 100% weaker to headshots but 10% resistant to everywhere else. Zombies cannot heal."
Class[Number]["health"] = 50
Class[Number]["armor"] = 50
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.9
Class[Number]["runspeedmul"] = 0.75
Class[Number]["jumpmul"] = 0.80
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.25
Class[Number]["perks"] = {"DeadLife","BrainDamage","ArcLight","Necro"}
Class[Number]["color"] = Color(180,125,125,255)
Class[Number]["icon"] = "models/Zombie/Classic.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Thief"
Class[Number]["description"] = "Counters anyone tanky and has the potential to become a tank. Thieves steal armor based on 15% of damage dealt up to 200, and health based on 20% of damage dealt up to 200. For every 2 points of health or armor, the player is slowed by 1%. Thieves also have special armor piercing bullets that do +1% more damage per point of enemy armor, but 50% less damage against enemies without armor. Thieves cannot heal."
Class[Number]["health"] = 50
Class[Number]["armor"] = 50
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 1.5
Class[Number]["runspeedmul"] = 1.5
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"LifeSteal","ArmorSteal","AP","Necro","SpeedChange"}
Class[Number]["color"] = Color(100,100,100,255)
Class[Number]["icon"] = "models/player/greenarrow.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Demon"
Class[Number]["description"] = "Balanced class for people who want to fight like a man and get rewarded for it. Demons trade life energy escaped from enemy wounds for bonus armor. For every 1 point of damage, 0.25 points of armor is added. Demons cannot heal."
Class[Number]["health"] = 75
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 1
Class[Number]["runspeedmul"] = 1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0.9
Class[Number]["perks"] = {"SoulAbsorb","Necro"}
Class[Number]["color"] = Color(150,0,150,255)
Class[Number]["icon"] = "models/player/hunter.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Void"
Class[Number]["description"] = "Counters people who are better than you, good for being a pain in the ass. Voids don't entirely exist in this plain of existence. Voids reflect 50% of damage done to them at the cost of 75% less base damage but cannot reflect damage done by other methods of damage reflection. Voids slowly take damage over time. Voids cannot be healed."
Class[Number]["health"] = 100
Class[Number]["armor"] = 10
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.9
Class[Number]["runspeedmul"] = 0.9
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0
Class[Number]["perks"] = {"ReflectDamage", "Annoying", "Necro"}
Class[Number]["color"] = Color(200,200,200,255)
Class[Number]["icon"] = "models/player/sunabouzu.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Phantom"
Class[Number]["description"] = "Counters people who like using sniper rifles, good for being a pain in the ass. Phantoms have a 25% chance to completely dodge an attack, and have a strange aura around them that causes people's vision to shake. Phantoms cannot be healed."
Class[Number]["health"] = 75
Class[Number]["armor"] = 25
Class[Number]["stamina"] = 25
Class[Number]["walkspeedmul"] = 1
Class[Number]["runspeedmul"] = 1.2
Class[Number]["jumpmul"] = 1.1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0
Class[Number]["perks"] = {"Evasion","Mystical","Necro"}
Class[Number]["color"] = Color(200,200,225,255)
Class[Number]["icon"] = "models/vinrax/player/jack_player.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Field Medic"
Class[Number]["description"] = "Doesn't really counter anything, but it's good in team deathmatch. Field Medics slowly restore 1 health every second to nearby allies on his team. This bonus is tripled on the medic. Medics also leech 1 point of health per second off of enemies in a 500 unit radius."
Class[Number]["health"] = 60
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 20
Class[Number]["walkspeedmul"] = 0.90
Class[Number]["runspeedmul"] = 1.1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"Medic","AuraLeech"}
Class[Number]["color"] = Color(255,10,10,255)
Class[Number]["icon"] = "models/Characters/Hostage_01.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Shredder"
Class[Number]["description"] = "Great with sniper rifles, even better for being a massive pain the ass. 3% of damage dealt to an enemy transfers to all other players on the map. If an enemy is under 3 health, the enemy takes massive damage and the Shredder takes credit for the kill, no matter how far or close he is. Shredders have a unique allow armor that removes the base damage dealt by 5, but multiplies any remaining damage by 2."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.8
Class[Number]["runspeedmul"] = 0.8
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.25
Class[Number]["perks"] = {"Splash","Bargain","GlobalKS"}
Class[Number]["color"] = Color(150,200,200,255)
Class[Number]["icon"] = "models/player/scarecrow.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Sniper"
Class[Number]["description"] = "Great with sniper rifles, specifically for the under appreciated scout sniper rifle. Gains the ability to grant critical strikes. Critical strikes stun your opponent for 0.25 seconds and do double damage. Every 2 points of base damage adds 1% chance to crit. Snipers also have a special type of shield amplification technology that expands when shot, causing snipers to resist 1% of all damage per 1 point of lost health, up to 50%, but causes the sniper's base damage to decrease by 50 but multiply by 3. "
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 30
Class[Number]["walkspeedmul"] = 0.5
Class[Number]["runspeedmul"] = 0.75
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 0.7
Class[Number]["fallmul"] = 0.8
Class[Number]["perks"] = {"Stunner","Survivor","Forced"}
Class[Number]["color"] = Color(100,200,0,255)
Class[Number]["icon"] = "models/player/azuisleet1.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Voltage"
Class[Number]["description"] = "Great for having longer lives. Volts have a strong shield regeneration core that restores shields up to 100, but causes the user to take 100% bonus damage on shield depletion."
Class[Number]["health"] = 100
Class[Number]["armor"] = 100
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.85
Class[Number]["runspeedmul"] = 0.85
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.5
Class[Number]["perks"] = {"ArmorDependant","ArmorRegen"}
Class[Number]["color"] = Color(0,100,0,255)
Class[Number]["icon"] = "models/player/teslapower.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Terrorist"
Class[Number]["description"] = "Terrorists have double the clipsize, but do 25% less damage. Terrorists also have C4 explosives attached to their chest, which detonates upon death."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.80
Class[Number]["runspeedmul"] = 0.80
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"Snackbar","Cannon"}
Class[Number]["color"] = Color(0,100,0,255)
Class[Number]["icon"] = "models/player/teslapower.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Predator"
Class[Number]["description"] = "Counters snipers, great for sniping and/or camping. Gains the cloak ability which drains 1 armor every 5 seconds. Cloak amount is based on movement speed. Each attack also steals armor based on 15% of damage dealt, Stacks up to 200 points of armor."
Class[Number]["health"] = 20
Class[Number]["armor"] = 100
Class[Number]["stamina"] = 30
Class[Number]["walkspeedmul"] = 0.5
Class[Number]["runspeedmul"] = 1.25
Class[Number]["jumpmul"] = 2
Class[Number]["crouchmul"] = 0.5
Class[Number]["fallmul"] = 0
Class[Number]["perks"] = {"Cloak","ArmorSteal"}
Class[Number]["color"] = Color(25,100,200,255)
Class[Number]["icon"] = "models/player/nuggets.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Trickster"
Class[Number]["description"] = "Counters anyone better than you, even better for being a massive pain in the ass. Tricksters can swap with any random player on the map once every 30 seconds if the Trickster's health is below 50. Explosive damage dealt by Tricksters turn into stackable stuns, for every 20 points of explosive damage, 1 second of stun is added. Tricksters cannot be healed."
Class[Number]["health"] = 125
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.90
Class[Number]["runspeedmul"] = 0.90
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 0
Class[Number]["perks"] = {"Swap","Trap","Necro"}
Class[Number]["color"] = Color(200,200,225,255)
Class[Number]["icon"] = "models/player/rorschach.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Spy"
Class[Number]["description"] = "Counters anyone better than you, even better against snipers. Spies can fake their death by creating a holographic corpse while turning invisible. The invisibility lasts until you damage someone. Spies grant a 100% critical strike chance while invisible. Spies cannot heal."
Class[Number]["health"] = 25
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 20
Class[Number]["walkspeedmul"] = 1
Class[Number]["runspeedmul"] = 1
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"FakeDeath","Necro"}
Class[Number]["color"] = Color(200,100,100,255)
Class[Number]["icon"] = "models/player/spy.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "NIGGER SLAYER"
Class[Number]["description"] = "Counters anyone better than you, great for being a tank and manfighting. I am justice incarnate, brought forth to end the lives of those that are wasting breathing air and purge them of their foul presence. I am the NIGGER SLAYER, and you're niggery ends here, now. Drop to your knees and surrender, or you will face a war machine unlike ANY this world has ever seen. Nigger slayers start off with high health that is multiplied by Deaths/Kills, but limited between 100-300 health. Nigger Slayers take damage over time but never under 25 health. 50 health is regained every kill up to a maximum of 300. Nigger Slayers cannot heal."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 10
Class[Number]["walkspeedmul"] = 0.65
Class[Number]["runspeedmul"] = 0.65
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 3
Class[Number]["perks"] = {"Slayer","Necro"}
Class[Number]["color"] = Color(255,233,127,255)
Class[Number]["icon"] = "models/serioussam/sam_stone_bfe.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Rambo"
Class[Number]["description"] = "Good for running around the map and being literally rambo. Gain 30% bonus damage at the cost of 30% more incoming damage. Rambos have an endless clip. "
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.1
Class[Number]["runspeedmul"] = 1.5
Class[Number]["jumpmul"] = 1
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"DamageTrade","Rambo"}
Class[Number]["color"] = Color(127, 111, 63,255)
Class[Number]["icon"] = "models/player/deadpool.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Supercharged"
Class[Number]["description"] = "Good for mobility, great for shotgun lovers, not so good in combat. Take 4 damage per second if you move, but heal 4 health per second if you stand still. Supercharged also gives armor based on movement speed, up to a maximum of 200. Cannot be healed by other means."
Class[Number]["health"] = 100
Class[Number]["armor"] = 0
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 1.75
Class[Number]["runspeedmul"] = 1.75
Class[Number]["jumpmul"] = 1.25
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1
Class[Number]["perks"] = {"Bleedout","Necro","SpeedShield"}
Class[Number]["color"] = Color(200, 100, 0,255)
Class[Number]["icon"] = "models/player/sam.mdl"

Number = Number + 1
Class[Number] = {}
Class[Number]["name"] = "Shatterling"
Class[Number]["description"] = "Counters small arm damage such as shotguns, great for people who like being a human tank, not so good against sniper rifles. As long as you have armor, each hit against you grants an entire second of damage immunity, during this immunity you are stunned. Immune to headshots. Takes 50% extra damage. Has a 10% chance to negate damage and heal for that amount. Shatterlings steal armor based on 15% of damage dealt. Shatterlings cannot heal."
Class[Number]["health"] = 100
Class[Number]["armor"] = 100
Class[Number]["stamina"] = 15
Class[Number]["walkspeedmul"] = 0.4
Class[Number]["runspeedmul"] = 0.4
Class[Number]["jumpmul"] = 0.75
Class[Number]["crouchmul"] = 1
Class[Number]["fallmul"] = 1.2
Class[Number]["perks"] = {"Shatter","Necro","Reversal","ArmorSteal"}
Class[Number]["color"] = Color(100, 50, 255,255)
Class[Number]["icon"] = "models/player/lordvipes/bl_clance/crimsonlanceplayer.mdl"